### ISSUE TITLE
Laplace Blur

### ISSUE THREAD

**Issue by xmichael** [cobweb-eu/cobweb-qa#2]
**About**
Indicates if an image is too blurry using a single parameter 0-100 as a threshold.

**Notes**
Refactoring work already done by Sam. It needs to be unit-tested and added to the new gradle build system.

**Comment by gmh04** [comment]
https://github.com/cobweb-eu/cobweb-qa/commit/19e2238b218d93da65fbbb401612df9d67d3ce54

**Comment by gmh04** [comment]
Current unit tests simply verifies one image is sharp and another is blurred with a threshold of 200.  May want to discuss more borderline cases, and in effect test the effectiveness/meaning of the threshold?

**Comment by xmichael** [comment]
It seems that the threshold is just a high-frequency barrier. The more high-frequencies the clearer the image. Unfortunately no documentation seems to be available AFAIK.

In any case it seems that this issue is complete
