### ISSUE TITLE
Line of Sight

### ISSUE THREAD

**Issue by xmichael** [cobweb-eu/cobweb-qa#3]
**About**
Takes elevation data (Lidar DTM/DSM), bearing, tilt, height of user, coords of user as parametres and returns coordinates and distance of targeted point.

**Notes**
- Refactoring work already done by Sam. It needs to be unit-tested and added to the new gradle build system.
- Only supports square rasters (same number of rows and columns).
  - “tilt=-1” means that the camera phone points 1° to the ground ie  -π⁄180 in radian.
  - bearing = 0 means North (0° in degrees)

**Comment by gmh04** [comment]
https://github.com/cobweb-eu/cobweb-qa/commit/a728aea3bd0c345d95d3a70a9e2a9c85a9593c0c

**Comment by gmh04** [comment]
Current unit test simply assets the output.  I would need help in more meaningful tests.

**Comment by xmichael** [comment]
Indeed but geometry-level debugging of the algorithm is outside the scope of this issue (and only concerns UNOTT).

This issue looks complete as it is (pending future bugfixes)
